services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./data/ZenDB.php:/var/www/html/systems/includes/includes/config/ZenDB.php
      - ./data/ZenPRIVATE.php:/var/www/html/systems/includes/includes/config/ZenPRIVATE.php
    depends_on:
      - db
    networks:
      - zencms-network

  db:
    image: mysql:5.7
    platform: linux/amd64
    command: --sql-mode=""
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zencms
      MYSQL_USER: zencms
      MYSQL_PASSWORD: zencmspassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - zencms-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8089:80"
    depends_on:
      - db
    networks:
      - zencms-network

volumes:
  db_data:

networks:
  zencms-network:
